routes:
  - path_prefix: /user
    methods:
      - POST
      - GET
      - PUT
    backends:
      - http://localhost:8001
      - http://localhost:8002
    health: /health
  - path_prefix: /settings
    backends:
      - http://localhost:8084
    health: /health
  - path_prefix: /profile
    backends:
      - http://localhost:8081
      - http://localhost:8082
      - http://localhost:8083
    methods:
      - GET
      - POST
      - DELETE
    health: /health

port: ":8080"
env: "development"
log_level: "INFO"

  
